### PR TITLE
Multi-arch, install via npm

### PR DESCRIPTION
**Pull request by aptalca**

### CODE REVIEW

**Comment by aptalca** [comment]
Errors in the log :(

**Comment by nemchik** [comment]
Ref: https://github.com/cdr/code-server/issues/1656

**Comment by aptalca** [comment]
I gotta update a couple of mods before merging this so we don't have broken stuff out there.

**Comment by nemchik** [comment]
> I gotta update a couple of mods before merging this so we don't have broken stuff out there.

Indeed some may need some multi-arch attention for sure.

**Comment by aptalca** [comment]
Mod multi-arch PRs:
https://github.com/linuxserver/docker-mods/pull/43
https://github.com/linuxserver/docker-mods/pull/42
https://github.com/linuxserver/docker-mods/pull/41

**Pull request merged**
