### PR TITLE
fix apply chown permissions in parallel for large workspace

### PR DESCRIPTION
**Pull request by gjrtimmer**
`chown` is always bound to a single core. See man page `chown`. Applying the permissions through a single process on a large workspace causes the container boot process to be slow. In order to mitigate slow container start times for large work spaces `chown` can be run in parallel. This PR provides that functionality.

## Gains
* Increase container boot time by a factor ~20
* Significant reduction in memory use on container start because the entire /config will not be loaded in a singular `chown` process which for a large config directory and/or workspace can easily increase to over 1.2 GB of additional memory.
* Automatic parallel process allocation based upon available cores

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-code-server/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
Apply permissions through `chown` in parallel.

## Benefits of this PR and context:
Benefits are pure speed when it comes to starting the container.

The following test results are from a workspace with the following details.
```bash
Files: 134,834
Size: 9.8 GB
```

### Results before PR
```bash
real    17m27.335s
user    0m1.222s
sys     0m50.652s
```

### Results after PR
```bash
# chown /config
real    0m15.775s
user    0m0.809s
sys     0m12.201s

# chown /config/workspace
real    0m33.875s
user    0m2.461s
sys     0m42.309s
```

## How Has This Been Tested?
* Container build
* prefixed command with linux `time` command, recorded differences and attached them in this PR.

### CODE REVIEW

**Comment by gjrtimmer** [comment]
[EDIT] Updated PR to include automatic process allocation based upon available number of cores in container

**Comment by gjrtimmer** [comment]
`58e865e` fixes the error found in the logs of `LinuxSever-CI`

### log
```bash
...
setting permissions::workspace
chown: missing operand after ‘abc:abc’
Try 'chown --help' for more information.
...
```

Fixed in `58e865e` do not run `xargs` when empty

**Comment by gjrtimmer** [comment]
@aptalca Ready for evaluation

**Comment by gjrtimmer** [comment]
@aptalca Any update ?

**Comment by aptalca** [comment]
@gjrtimmer thanks for the PR. I've been quite busy with real life and other projects.
I did do a quick review and it looks good.

To be honest, when I first put in the chown in there, I didn't consider that folks may have many gigs of data in the config folder. In such cases (like plex or emby where they have hundreds of gigs), we usually check the top folder and if the perms there are good, we skip the chown.

I'm thinking we can do the same here for the workspace folder, where we check `/config/workspace` and skip its subfolders if its perms are good. The rest of the config folder can be chowned via xargs.

It also got me thinking, since we provide sudo/root access in this container, the user may have files in workspace with different perms or owners intentionally. We certainly don't want to mess with them.

Let me know if you see any issues with that plan. If not, please modify it accordingly (only chown `/config/workspace` if needed, and not recursive, and the rest of `/config` can be chowned recursively).

Thanks

**Comment by gjrtimmer** [comment]
@aptalca I totally understand, I work myself in medical IT, so I know how taxing real life can be. Your suggestions got me also thinking, what if we make a few changes and introduce some variables, this way we can do even both, have the user decide and provide some flexibility which even can be ported to other containers. I will change the PR according to your suggestions, and keep your initial suggestion as the default action.

**Comment by Roxedus** [comment]
> I've noticed something really weird, did you know that the base image sets the user for the custom-cont-init.d and custom-services.d to root:root even if the users creates the directories; is that a bug ?

No this is intended, to block compromised apps to be able to write to files that are executed by root. 

I can also mention that I mounted my projects to another folder, mainly because my /config is backed up.

**Comment by gjrtimmer** [comment]
@Roxedus Thank you.

**Comment by gjrtimmer** [comment]
@aptalca | @Roxedus | Request review

**Comment by aptalca** [comment]
I'm not in favor of adding an env var (let alone 2) for permissions. I think we should simply chown everything under config recursively except for workspace, which we'll chown non-recursive (so code-server can access it on start). Anything inside workspace will be the user's own responsibility.

**Comment by gjrtimmer** [comment]
@aptalca | I understand, will provide fix within 5m

**Comment by aptalca** [comment]
Thanks so much. While you're at it, can you also update the changelog entry to today's date?

**Comment by gjrtimmer** [comment]
@aptalca | Fix provided, corrections made upon comments, please review

**Comment by gjrtimmer** [comment]
@aptalca during the rewrite, I forget to put the `--null` back in. Fix is building. Request review

**Comment by gjrtimmer** [comment]
@aptalca DONE

**Pull request merged**
