### PR TITLE
Add support for --proxy-domain

### PR DESCRIPTION
**Pull request by n-i-x**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

 

------------------------------

We welcome all PR’s though this doesn’t guarantee it will be accepted.

## Description:
Add --proxy-domain args to start args

## Benefits of this PR and context:
code-server supports subdomain-based proxying of internal ports. In order to support this, the --proxy-domain arg needs to be set.

## How Has This Been Tested?
Container built with this support and run. Redacted relevant log output here:

```
info  code-server 3.2.0 fd36a99a4c78669970ebc4eb05768293b657716f
info  HTTP server listening on http://0.0.0.0:8443
info    - No authentication
info    - Not serving HTTPS
info    - Proxying the following domain:
info      - *.code-server.my.domain
info  Automatic updates are disabled
```

## Source / References:

https://github.com/cdr/code-server/blob/master/doc/FAQ.md#sub-domains

### CODE REVIEW

**Comment by n-i-x** [comment]
FYI... the Jenkins build for code-server is broken. There are no linux-x86_64 assets since 3.2.0... code-server broke something.

**Comment by aptalca** [comment]
Yup, see #28

**Comment by dompl** [comment]
Hi,

Are you guys planning on working this out?

Thanks

**Comment by jrebey** [comment]
I needed to merge in the latest changes, that's been done. This can be merged now.

**Pull request merged**
