### PR TITLE
Do not corrupt permissions inside workspace

### PR DESCRIPTION
**Pull request by andrewshulgin**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-code-server/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Currentry, workspace permissions are being reassigned on each container run. I bet it's not the expected behaviour. Furthermore, the comment in else block describes that workspace should be omitted. This PR fixes the find command options so that it excludes `/config/workspace` and the root `/config` directory.

This repeats #99, but with a new source branch name.

## Benefits of this PR and context:

Fixes unexpected behaviour described above.

## How Has This Been Tested?

- Built and ran the container with the changes applied. File permissions inside the container weren't attempted to be changed.
- Ran the container with a read-only mount attached to `/config/workspace`. There were no startup errors.

### CODE REVIEW

**Comment by wbenny** [comment]
Thanks! Hopefully this will be merged ASAP. It's really awful bug.

**Comment by andrewshulgin** [comment]
As I can see, the issue is still relevant. Dear maintainers, could you please merge this PR?

**Comment by wbenny** [comment]
+1

**Comment by aptalca** [comment]
Can you guys please test this image? Make sure to back up first.
`lspipepr/code-server:4.7.0-pkg-112f9952-pr-125`
It has various updates including a rebase to jammy and s6v3, along with a brand new chown logic

Thanks

**Pull request closed without merging**
