### PR TITLE
Add support for --locale

### PR DESCRIPTION
**Pull request by MalsonQu**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-code-server/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Add optional option --locale in file `root/etc/services.d/code-server/run` to set language for code-server by manual.
This is [Available locales](https://code.visualstudio.com/docs/getstarted/locales#_available-locales)
**it is very important to Chinese people :D**.

## Benefits of this PR and context:

easy to change language for code-server

## How Has This Been Tested?

just when run image, set env `LOCALE` like `zh-CN`, when container started install Language Pack in code-server like `Chinese (Simplified) Language Pack for Visual Studio Code`. restart the container will see language changed to Simplified chinese

### CODE REVIEW

**Comment by aptalca** [comment]
Thanks for the PR, but can't you change the locale in the gui? I mean, all our docs and everything is in English. If someone is able to follow our docs to create the container, I'd assume they would be able to change the locale in the gui?

I'd really like to keep the env vars to a minimum.

**Comment by MalsonQu** [comment]
thanks for reply.
I've tried many times
- Install Language Pack and set Display language to non English.  Restart container. It’s display English.
- Create file argv.json and input option locale. Restart container. It’s display English.
- Create file locale.json and input option locale. Restart container. It’s display English.

I also not want change env to keep minimum.
But when I change file root/etc/services.d/code-server/run it’s displayed my language.

So I created this pull request.

If have others way to change language. Please tell me. I really need it

**Comment by aptalca** [comment]
It seems to be a code server issue. They have been changing a lot of things lately and the language selection in the gui is not working properly: https://github.com/cdr/code-server/issues/215

However, you can change the locale by putting a `locale.json` file under `/config/data/User`, which contains all code-server user data (which is where the gui setting should write it, but doesn't)

**Comment by MalsonQu** [comment]
yes! you are right, put file `locale.json` file under `/config/data/User` is work,but need lowercase like `zh-cn`

**Comment by MalsonQu** [comment]
Thank you very muc

**Pull request closed without merging**
