### PR TITLE
Fix not applied SUDO_PASSWORD_HASH env var

### PR DESCRIPTION
**Pull request by leey0818**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-code-server/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Fixed to use `chpasswd` instead of `sed` to set sudo password hash.

### CODE REVIEW

**Comment by leey0818** [comment]
Is there anything else I need to do?

**Comment by leey0818** [comment]
Please reply this pr

**Comment by yuntsewu** [comment]
please merge this soon, this error eventually crashes application server

**Comment by aptalca** [comment]
What error?

**Comment by syepes** [comment]
+1 For fixing this

**Pull request closed without merging**
