### PR TITLE
Do not corrupt permissions inside workspace

### PR DESCRIPTION
**Pull request by andrewshulgin**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-code-server/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Currentry, workspace permissions are being reassigned on each container run. I bet it's not the expected behaviour. Furthermore, the comment in else block describes that workspace should be omitted. This PR fixes the find command options so that it excludes `/config/workspace` and the root `/config` directory.

## Benefits of this PR and context:

Fixes unexpected behaviour described above.

## How Has This Been Tested?

- Built and ran the container with the changes applied. File permissions inside the container weren't attempted to be changed.
- Ran the container with a read-only mount attached to `/config/workspace`. There were no startup errors.

### CODE REVIEW

**Comment by n-i-x** [comment]
yes please! I've got a lot of files in my workspace and starting up code-server takes about an hour! I have to login and kill the chown in order to get the UI started. It also messes with files I stage for embedded linux releases as it does a chown to the abc user which isn't always what I want.

**Comment by aptalca** [comment]
Thanks for the PR. The intention of that code block was to ignore workspace in the recursive chown and only do a non-recursive on it but a local test shows it isn't working properly.

@gjrtimmer I believe you had PRed that code block. Did you have any comments on the proposed changes?

Thanks

**Comment by andrewshulgin** [comment]
> but a local test shows it isn't working properly.

I'd want to clarify, your local test confirms the issue in the master branch or it shows improper behaviour of my changes?

**Comment by andrewshulgin** [comment]
@aptalca Hello! It has been a while since I've submitted this PR. Is there any chance that this PR will be merged?

**Comment by gjrtimmer** [comment]
No comments about the PR

**Pull request closed without merging**
